language: php

dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly

env:
  matrix:
  - DOCTRINE_ORM_VERSION=~2.1.0
  - DOCTRINE_ORM_VERSION=~2.2.0
  - DOCTRINE_ORM_VERSION=~2.3.0
  - DOCTRINE_ORM_VERSION=~2.4.0

matrix:
  exclude:
  - php: nightly
    env: DOCTRINE_ORM_VERSION=~2.1.0
  - php: nightly
    env: DOCTRINE_ORM_VERSION=~2.2.0
  - php: nightly
    env: DOCTRINE_ORM_VERSION=~2.3.0
  allow_failures:
  - php: nightly

install: composer require "doctrine/orm:${DOCTRINE_ORM_VERSION}"

script: vendor/bin/phpunit

notifications:
  email:
    recipients:
      secure: GB+W4AQDJv8WkRp2L9C36ukQxFkMXZ0Z8Qe18hIUdTrjn+aK9ywj/jnDTIKIPKNxyh+9Zql2PoacQN8HArKpztcWYBuwpWos1Lk6pJwTzLuTO7XzatC+x80K9SOud4NC+ALQI1onfP07yjkftSRbwzpI5h+AydQIPNuKiN4BVkA=
